---
- name: ASA ACL
  connection: network_cli
  gather_facts: false
  hosts: dexa-asa01
  become: yes
  become_method: enable
  
  vars_files:
    - defaults/credentials.yml

  collections:
    - cisco.asa

  tasks:
    - name: acl for new speedup service
      cisco.asa.asa_config:
        lines:
        - access-list DehongStaffPermit extended permit ip object-group DehongStaffNetwork host 1.1.1.1 inactive
        save: yes